import { sanitizeInput } from '@/lib/sanitize';

/**
 * Marketing footer for free templates
 * Includes attribution to Vyndi AI, upsell message, and homepage link
 */
export function renderMarketingFooter(homepageUrl: string = 'https://vyndi.hu'): string {
  const safeUrl = sanitizeInput(homepageUrl);
  const brandName = 'Vyndi AI';
  const upsellMessage = 'Upgrade to Pro for premium templates and advanced features.';
  const linkText = 'Visit Vyndi AI';

  return `
    <div class="offer-doc__marketing-footer">
      <p class="offer-doc__marketing-text">
        This offer was generated by <strong>${sanitizeInput(brandName)}</strong>. 
        ${sanitizeInput(upsellMessage)} 
        <a href="${safeUrl}" class="offer-doc__marketing-link" target="_blank" rel="noopener noreferrer">${sanitizeInput(linkText)}</a>
      </p>
    </div>
  `;
}







