/**
 * Wizard configuration constants
 */
export const WIZARD_CONFIG = {
  MAX_PREVIEW_RETRIES: 2,
  MAX_IMAGE_COUNT: 3,
  MAX_IMAGE_SIZE_BYTES: 2 * 1024 * 1024,
  PREVIEW_TIMEOUT_MS: 30000,
  PREVIEW_MIN_HEIGHT_PX: 720,
  PREVIEW_DEBOUNCE_MS: 500,
  VALIDATION_DEBOUNCE_MS: 300,
  AUTO_SAVE_DELAY_MS: 2000,
} as const;

export const MAX_IMAGE_SIZE_MB = Math.round(
  (WIZARD_CONFIG.MAX_IMAGE_SIZE_BYTES / (1024 * 1024)) * 10,
) / 10;




